name = "nanoo-cdn"
main = "index.js"
compatibility_date = "2024-04-17"

[vars]
B2_APPLICATION_KEY_ID = "0038f4a4d378b380000000002"
B2_ENDPOINT = "s3.eu-central-003.backblazeb2.com"
BUCKET_NAME = "nanoo-assets"
ALLOW_LIST_BUCKET = "false"

[[routes]]
pattern = "cdn.nanoo.cloud"
custom_domain = true